/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.ferracini.argentum.modelo;

public class App {
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public String getGreeting() {
        return "Hello world.";
    }
}
